export interface Park {
    id: number;
    reference: string;
    name: string;
    grid6: string;
    active: boolean;
    latitude: number;
    longitude: number;
    parkComments: string;
    parktypeId: number;
    parktypeDesc: string;
    locationDesc: string;
    locationName: string;
    entityName: string;
    accessMethods: string;
    activationMethods: string;
    firstActivator: string;
    firstActivationDate: string;
    website: string;
};