export interface SpotRow {
    spotId: number,
    activator: string,
    frequency: string,
    mode: string,
    reference: string,
    parkName: any,
    spotTime: string,
    spotter: string,
    comments: string,
    source: string,
    invalid: any,
    name: string,
    locationDesc: string,
    grid4: string,
    grid6: string,
    latitude: number
    longitude: number,
    count: number,
    expire: number,
    hunted: boolean,
    hunted_bands: string,
    park_hunts: number,
    op_hunts: number,
    loc_hunts: number,
    loc_total: number,
    is_qrt: boolean
};
